#!/bin/sh

# PROVIDE: my_app
# REQUIRE: NETWORKING SERVERS DAEMON
# BEFORE:  LOGIN
# KEYWORD: shutdown

# Taken from http://habrahabr.ru/post/137857/

. /etc/rc.subr

name="my_app"
forever="/usr/local/bin/node /usr/local/bin/forever"
workdir="/usr/local/www"
script="${workdir}/${name}/main.js"

rcvar="${name}_enable"
extra_commands="status"

start_cmd="start"
status_cmd="status"
stop_cmd="stop"
restart_cmd="restart"

load_rc_config $name
eval "${rcvar}=\${${rcvar}:-'NO'}"

HOME=/var/run/node
start()
{
  export NODE_ENV
  export PORT
  export ROOT_URL
  export MONGO_URL
  su -m www -c "exec ${forever} start -a -l /var/log/node/${name}.log -o /dev/null -e /var/log/node/err.log -p ${HOME} ${script}"
}

status()
{
  su -m www -c "exec ${forever} list"
}

stop()
{
  su -m www -c "exec ${forever} stop ${script}"
}

restart()
{
  su -m www -c "exec ${forever} restart ${script}"
}

run_rc_command "$1"
